"""Create the initial horse-racing schema

Revision ID: 20260821_0001
Revises:
Create Date: 2026-08-21 17:04:09.380340
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260821_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "horses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kra_horse_id", sa.String(length=30), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=150), nullable=True),
        sa.Column("sex", sa.String(length=20), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("origin_country", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_horses")),
        sa.UniqueConstraint("kra_horse_id", name=op.f("uq_horses_kra_horse_id")),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("data_type", sa.String(length=100), nullable=False),
        sa.Column("started_at_ms", sa.BigInteger(), nullable=False),
        sa.Column("completed_at_ms", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("records_fetched", sa.Integer(), nullable=False),
        sa.Column("records_written", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed', 'partial')",
            name=op.f("ck_ingestion_runs_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_table(
        "jockeys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kra_jockey_id", sa.String(length=30), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=150), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jockeys")),
        sa.UniqueConstraint("kra_jockey_id", name=op.f("uq_jockeys_kra_jockey_id")),
    )
    op.create_table(
        "owners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kra_owner_id", sa.String(length=30), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=150), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_owners")),
        sa.UniqueConstraint("kra_owner_id", name=op.f("uq_owners_kra_owner_id")),
    )
    op.create_table(
        "racecourses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kra_meet_code", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name_ko", sa.String(length=50), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_racecourses")),
        sa.UniqueConstraint("code", name=op.f("uq_racecourses_code")),
        sa.UniqueConstraint("kra_meet_code", name=op.f("uq_racecourses_kra_meet_code")),
    )
    op.create_table(
        "trainers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kra_trainer_id", sa.String(length=30), nullable=False),
        sa.Column("name_ko", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=150), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trainers")),
        sa.UniqueConstraint("kra_trainer_id", name=op.f("uq_trainers_kra_trainer_id")),
    )
    op.create_table(
        "races",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("racecourse_id", sa.Integer(), nullable=False),
        sa.Column("race_date_local", sa.Date(), nullable=False),
        sa.Column("race_number", sa.Integer(), nullable=False),
        sa.Column("distance_m", sa.Integer(), nullable=False),
        sa.Column("grade", sa.String(length=50), nullable=True),
        sa.Column("race_name", sa.String(length=200), nullable=True),
        sa.Column("scheduled_at_ms", sa.BigInteger(), nullable=True),
        sa.Column("weather", sa.String(length=30), nullable=True),
        sa.Column("track_condition", sa.String(length=30), nullable=True),
        sa.Column("track_moisture_percent", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint("distance_m > 0", name=op.f("ck_races_positive_distance")),
        sa.CheckConstraint("race_number > 0", name=op.f("ck_races_positive_race_number")),
        sa.ForeignKeyConstraint(
            ["racecourse_id"],
            ["racecourses.id"],
            name=op.f("fk_races_racecourse_id_racecourses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_races")),
        sa.UniqueConstraint(
            "racecourse_id", "race_date_local", "race_number", name="race_identity"
        ),
    )
    with op.batch_alter_table("races", schema=None) as batch_op:
        batch_op.create_index(
            "ix_races_date_course", ["race_date_local", "racecourse_id"], unique=False
        )

    op.create_table(
        "source_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("retrieved_at_ms", sa.BigInteger(), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("local_path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_source_documents_ingestion_run_id_ingestion_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
        sa.UniqueConstraint("source_url", "sha256", name="source_url_sha256"),
    )
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.create_index(
            "ix_source_documents_retrieved_at_ms", ["retrieved_at_ms"], unique=False
        )

    op.create_table(
        "odds_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("bet_type", sa.String(length=30), nullable=False),
        sa.Column("selection_key", sa.String(length=50), nullable=False),
        sa.Column("odds", sa.Float(), nullable=False),
        sa.Column("observed_at_ms", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("odds > 0", name=op.f("ck_odds_snapshots_positive_odds")),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
            name=op.f("fk_odds_snapshots_race_id_races"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_odds_snapshots")),
        sa.UniqueConstraint(
            "race_id", "bet_type", "selection_key", "observed_at_ms", name="odds_observation"
        ),
    )
    with op.batch_alter_table("odds_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_odds_snapshots_race_time", ["race_id", "observed_at_ms"], unique=False
        )

    op.create_table(
        "race_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("horse_id", sa.Integer(), nullable=False),
        sa.Column("jockey_id", sa.Integer(), nullable=True),
        sa.Column("trainer_id", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("horse_number", sa.Integer(), nullable=False),
        sa.Column("gate_number", sa.Integer(), nullable=True),
        sa.Column("carried_weight_kg", sa.Float(), nullable=True),
        sa.Column("body_weight_kg", sa.Integer(), nullable=True),
        sa.Column("body_weight_change_kg", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("running_style", sa.String(length=30), nullable=True),
        sa.Column("scratched", sa.Boolean(), nullable=False),
        sa.CheckConstraint("horse_number > 0", name=op.f("ck_race_entries_positive_horse_number")),
        sa.ForeignKeyConstraint(
            ["horse_id"],
            ["horses.id"],
            name=op.f("fk_race_entries_horse_id_horses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["jockey_id"], ["jockeys.id"], name=op.f("fk_race_entries_jockey_id_jockeys")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["owners.id"], name=op.f("fk_race_entries_owner_id_owners")
        ),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
            name=op.f("fk_race_entries_race_id_races"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"], ["trainers.id"], name=op.f("fk_race_entries_trainer_id_trainers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_race_entries")),
        sa.UniqueConstraint("race_id", "horse_id", name="race_horse"),
        sa.UniqueConstraint("race_id", "horse_number", name="race_horse_number"),
    )
    with op.batch_alter_table("race_entries", schema=None) as batch_op:
        batch_op.create_index("ix_race_entries_horse_race", ["horse_id", "race_id"], unique=False)

    op.create_table(
        "race_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_entry_id", sa.Integer(), nullable=False),
        sa.Column("finish_position", sa.Integer(), nullable=True),
        sa.Column("finish_time_ms", sa.Integer(), nullable=True),
        sa.Column("margin_text", sa.String(length=50), nullable=True),
        sa.Column("prize_money_krw", sa.BigInteger(), nullable=True),
        sa.Column("disqualified", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "finish_position IS NULL OR finish_position > 0",
            name=op.f("ck_race_results_positive_finish_position"),
        ),
        sa.CheckConstraint(
            "finish_time_ms IS NULL OR finish_time_ms > 0",
            name=op.f("ck_race_results_positive_time"),
        ),
        sa.ForeignKeyConstraint(
            ["race_entry_id"],
            ["race_entries.id"],
            name=op.f("fk_race_results_race_entry_id_race_entries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_race_results")),
        sa.UniqueConstraint("race_entry_id", name=op.f("uq_race_results_race_entry_id")),
    )
    op.create_table(
        "race_section_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_entry_id", sa.Integer(), nullable=False),
        sa.Column("section_code", sa.String(length=20), nullable=False),
        sa.Column("distance_from_start_m", sa.Integer(), nullable=True),
        sa.Column("elapsed_time_ms", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("gap_to_leader_lengths", sa.Float(), nullable=True),
        sa.Column("group_notation_raw", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "distance_from_start_m IS NULL OR distance_from_start_m >= 0",
            name=op.f("ck_race_section_results_nonnegative_distance"),
        ),
        sa.CheckConstraint(
            "position IS NULL OR position > 0",
            name=op.f("ck_race_section_results_positive_position"),
        ),
        sa.ForeignKeyConstraint(
            ["race_entry_id"],
            ["race_entries.id"],
            name=op.f("fk_race_section_results_race_entry_id_race_entries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_race_section_results")),
        sa.UniqueConstraint("race_entry_id", "section_code", name="entry_section"),
    )
    with op.batch_alter_table("race_section_results", schema=None) as batch_op:
        batch_op.create_index("ix_race_section_results_code", ["section_code"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("race_section_results", schema=None) as batch_op:
        batch_op.drop_index("ix_race_section_results_code")

    op.drop_table("race_section_results")
    op.drop_table("race_results")
    with op.batch_alter_table("race_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_race_entries_horse_race")

    op.drop_table("race_entries")
    with op.batch_alter_table("odds_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_odds_snapshots_race_time")

    op.drop_table("odds_snapshots")
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.drop_index("ix_source_documents_retrieved_at_ms")

    op.drop_table("source_documents")
    with op.batch_alter_table("races", schema=None) as batch_op:
        batch_op.drop_index("ix_races_date_course")

    op.drop_table("races")
    op.drop_table("trainers")
    op.drop_table("racecourses")
    op.drop_table("owners")
    op.drop_table("jockeys")
    op.drop_table("ingestion_runs")
    op.drop_table("horses")
    # ### end Alembic commands ###
