#!/usr/bin/env python3
"""Generate the Supabase PostgreSQL schema from SQLAlchemy metadata."""

from __future__ import annotations

import argparse
from pathlib import Path

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from horse_racing.db import models  # noqa: F401
from horse_racing.db.base import Base


def render_schema() -> str:
    dialect = postgresql.dialect()
    tables = list(Base.metadata.sorted_tables)
    table_names = [table.name for table in tables]

    statements = [
        "-- Generated by scripts/generate_supabase_schema.py; do not edit by hand.",
        "-- Application tables remain inaccessible through the Supabase Data API.",
        "SET search_path TO public, extensions;",
    ]
    for table in tables:
        statements.append(str(CreateTable(table).compile(dialect=dialect)).strip())
        for index in sorted(table.indexes, key=lambda item: item.name or ""):
            statements.append(str(CreateIndex(index).compile(dialect=dialect)).strip())

    quoted_names = ", ".join(f"'{name}'" for name in table_names)
    statements.append(
        """
CREATE FUNCTION public.prevent_prediction_ledger_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $$
BEGIN
    RAISE EXCEPTION 'immutable prediction ledger';
END;
$$
""".strip()
    )
    for table_name in (
        "prediction_runs",
        "model_predictions",
        "prediction_model_components",
        "model_prediction_explanations",
        "prediction_settlements",
        "prediction_outcomes",
    ):
        statements.append(
            f"""
CREATE TRIGGER trg_{table_name}_immutable
BEFORE UPDATE OR DELETE ON public.{table_name}
FOR EACH ROW EXECUTE FUNCTION public.prevent_prediction_ledger_mutation()
""".strip()
        )

    statements.append(
        f"""
DO $migration$
DECLARE
    app_table text;
    app_sequence text;
BEGIN
    FOREACH app_table IN ARRAY ARRAY[{quoted_names}]
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', app_table);
        EXECUTE format(
            'REVOKE ALL PRIVILEGES ON TABLE public.%I FROM PUBLIC, anon, authenticated',
            app_table
        );
        app_sequence := pg_get_serial_sequence(format('public.%I', app_table), 'id');
        IF app_sequence IS NOT NULL THEN
            EXECUTE format(
                'REVOKE ALL PRIVILEGES ON SEQUENCE %s FROM PUBLIC, anon, authenticated',
                app_sequence
            );
        END IF;
    END LOOP;
END;
$migration$
""".strip()
    )
    statements.extend(
        [
            "REVOKE EXECUTE ON FUNCTION public.prevent_prediction_ledger_mutation() FROM PUBLIC",
            (
                "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
                "REVOKE ALL PRIVILEGES ON TABLES FROM PUBLIC, anon, authenticated"
            ),
            (
                "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
                "REVOKE ALL PRIVILEGES ON SEQUENCES FROM PUBLIC, anon, authenticated"
            ),
        ]
    )
    return ";\n\n".join(statements) + ";\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    args.output.write_text(render_schema(), encoding="utf-8")
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
